[package]
authors = ["rchaser53 <tayoshizawa29@gmail.com>"]
name = "nyan"
version = "0.1.0"

[dependencies]
iron = "0.5.1"
mount = "0.3.0"
router = "0.5.1"
staticfile = "0.4.0"
time = "0.1.38"

[lib]
crate-type = ["dylib"]
name = "nyan"
path = "./src/main.rs"
